export const APPURL = process.env.REACT_APP_DRIVE_POST

export const FIREBASECONFIG ={
   apiKey: "AIzaSyDimftwPf8BJQKgRPs8kpYYol_ul59K3WA",
   authDomain: "comunidad-fiuba-3077f.firebaseapp.com",
   projectId: "comunidad-fiuba-3077f",
   storageBucket: "comunidad-fiuba-3077f.appspot.com",
   messagingSenderId: "86678440306",
   appId: "1:86678440306:web:210a097b576ed1be95b5eb",
   measurementId: "G-N76NBTSNCZ"
}
export const ACCEPTEDFILES = ["image/png", "image/jpg", "image/jpeg", "application/pdf"]

export const POSTDESTACADO = [61,96,42]

export const MATERIASREMPLAZABLES = ["Fisica I A"]
export const MATERIASREMPLAZO = ["Fisica I"]

export const FRASES_1 = ["¡Bienvenido!","¡Unite Ya!","¡Hola!","¡Alfin!","¡Llegaste!"]
export const FRASES_2 = ["Solo faltabas vos","Te estuvimos esperando","Te extrañamos",
   "Somos mas de 1000!","Esperamos que te guste"]

export const MATERIAS = [
   "Analisis Matematico II",
   "Probabilidad y Estadistica",
   "Matematica Discreta",
   "Algebra II",
   "Probabilidad y Estadistica B",
   "Analisis Matematico III A",
   "Analisis Matematico III C",
   "Matematica Especial para Ingenieria Quimica",
   "Matematica para Ingenieros",
   "Ecuaciones Diferenciales Ordinarias",
   "Analisis Funcional",
   "Algebra II C",
   "Fisica II A",
   "Fisica II B",
   "Mecanica I",
   "Mecanica II",
   "Mecanica Racional",
   "Fisica III C",
   "Fisica III D",
   "Fisica de los Fluidos",
   "Quimica",
   "Quimica I",
   "Quimica Analitica",
   "Quimica Fisica II",
   "Termodinamica Estadistica",
   "Quimica Inorganica",
   "Quimica Organica",
   "Quimica Analitica Instrumental",
   "Quimica Fisica",
   "Estatica y Resistencia de Materiales B",
   "Estabilidad I B",
   "Estabilidad II B",
   "Estabilidad III B",
   "Metodo de los Elementos Finitos",
   "Estabilidad IV B",
   "Analisis Experimental de Tensiones",
   "Electrotecnia General B",
   "Maquinas Electricas",
   "Electrotecnia General D",
   "Ingenieria de las Instalaciones I",
   "Laboratorio de Instalaciones Electricas",
   "Laboratorio",
   "Electronica General",
   "Electronica I",
   "Electronica II",
   "Analisis de Circuitos",
   "Circuitos Electronicos I",
   "Laboratorio de Microcomputadoras",
   "Sistemas Digitales",
   "Teoria de Control I",
   "Circuitos de Pulsos",
   "Organizacion de Computadoras",
   "Teoria de la Informacion y Codificacion",
   "Arquitecturas Paralelas",
   "Robotica",
   "Tecnica Digital Avanzada",
   "Procesamiento del Habla",
   "Procesamiento de Imagenes",
   "Sistemas Biologicos",
   "Simulacion de Sistemas de Control",
   "Redes Neuronales",
   "Criptografia y Seguridad Informatica",
   "Estructura del Computador",
   "Sistemas Graficos",
   "Señales y Sistemas",
   "Procesos Estocasticos",
   "Tesis de Ingenieria Mecanica",
   "Medios de Representacion B",
   "Termodinamica I A",
   "Dibujo Mecanico",
   "Mecanismos A",
   "Mecanismos B",
   "Conocimiento de Materiales I",
   "Conocimiento de Materiales II",
   "Tecnologia Mecanica I",
   "Ensayos Industriales",
   "Taller",
   "Mecanica de Fluidos B",
   "Maquinas Alternativas",
   "Turbomaquinas",
   "Mediciones Fisicas y Mecanicas",
   "Sistemas de Control",
   "Conversion de la Energia",
   "Proyecto de Instalaciones Industriales",
   "Elementos de Maquinas",
   "Metrologia",
   "Tecnologia Mecanica II",
   "Sistemas Hidraulicos y Neumaticos",
   "Proyecto de Maquinas",
   "Combustion",
   "Transferencia de Calor y Masa",
   "Tecnologia del Frio",
   "Tecnologia del Calor",
   "Proyecto de Instalaciones Termicas",
   "Tecnologia Mecanica B",
   "Dibujo para Ingenieros",
   "Diseño de Maquinas Herramientas",
   "Automotores",
   "Control Numerico de Maquinas Herramientas",
   "Robotica Industrial",
   "Plantas Termicas",
   "Sistemas de Control en Instalaciones Termicas",
   "Diseño de Instalaciones Termicas",
   "Metalografia",
   "Tratamientos Termicos",
   "Metalurgia Fisica",
   "Materiales Ferrosos y sus Aplicaciones",
   "Tecnicas Energeticas",
   "Elementos Finitos Avanzados en la Mecanica de Fluidos",
   "Introduccion al Metodo de los Elementos Finitos",
   "Mecanica del Continuo",
   "Introduccion al Analisis Tensorial",
   "Fundamentos Matematicos de la Vision en Robotica",
   "Elementos Finitos Avanzados",
   "Trabajo Profesional de Ingenieria Mecanica",
   "Puertos y Vias Navegables",
   "Transporte A",
   "Planeamiento del Transporte",
   "Ordenamiento Rural y Urbano",
   "Tesis de Ingenieria en Agrimensura",
   "Geometria Descriptiva",
   "Dibujo Topografico",
   "Geografia Fisica y Geologia",
   "Calculo De Compensacion",
   "Topografia I",
   "Topografia II",
   "Geodesia I",
   "Geodesia II",
   "Fotogrametria I",
   "Cartografia",
   "Fotogrametria II",
   "Geodesia III",
   "Levantamientos Hidrograficos",
   "Hidraulica Agricola y Saneamiento",
   "Catastro",
   "Informacion Rural",
   "Sistemas de Informacion Geografica",
   "Elementos de Construccion",
   "Topografia III",
   "Topografia IV",
   "Sistemas Cartograficos y Teledeteccion",
   "Levantamiento y Practica Profesional I",
   "Levantamiento y Practica Profesional II",
   "Valuaciones",
   "Geologia Aplicada",
   "Oceanografia Fisica",
   "Sistemas de Informacion Geografica II",
   "Topografia De Obra",
   "Dibujo Topografico II",
   "Trabajo Profesional de la Ingenieria en Agrimensura",
   "Introduccion a la Economia y Organizacion de la Empresa",
   "Agrimensura Legal I",
   "Estadistica Tecnica",
   "Investigacion Operativa",
   "Estructura de las Organizaciones",
   "Informacion en las Organizaciones",
   "Modelos y Optimizacion I",
   "Modelos y Optimizacion II",
   "Administracion de Proyectos",
   "Derecho Informatico",
   "Estructura Economica Argentina",
   "Modelos y Optimizacion III",
   "Economia",
   "Agrimensura Legal II",
   "Legislacion y Ejercicio Profesional de la Ingenieria Mecanica",
   "Legislacion y Ejercicio Profesional de la Ingenieria Quimica",
   "Agrimensura Legal III",
   "Organizacion de la Produccion",
   "Comercializacion",
   "Gestion Presupuestaria",
   "Gestion de Calidad",
   "Legislacion General",
   "Legislacion y Ejercicio Profesional de la Ingenieria en Informatica",
   "Analisis y Resolucion de Problemas",
   "Circuitos de Informacion en la Empresa",
   "Logistica Integral",
   "Recursos Humanos",
   "Ingenieria Economica",
   "Ingenieria Economica I",
   "Ingenieria Economica II",
   "Agrimensura Legal IV",
   "Evaluacion de Proyectos de Plantas Quimicas",
   "Economia de la Empresa Alimentaria",
   "Legislacion y Ejercicio Profesional de la Ingenieria de Alimentos",
   "Analisis y Resolucion de Problemas de Sistemas",
   "Materiales Industriales I",
   "Automatizacion Industrial",
   "Diseño de Producto",
   "Tesis de Ingenieria Naval y Mecanica",
   "Arquitectura Naval I",
   "Construccion Naval I",
   "Arquitectura Naval II",
   "Estructura de Buques",
   "Introduccion a Maquinas Marinas",
   "Vibraciones de Estructuras",
   "Construccion Naval II",
   "Proyecto de Buques I",
   "Proyecto de Buques II",
   "Maquinas Marinas I",
   "Maquinas Marinas II",
   "Navegacion",
   "Maquinas Marinas III",
   "Construccion Naval III",
   "Practicas en Astilleros I",
   "Practicas en Astilleros II",
   "Trabajo Profesional de Ingenieria Naval y Mecanica",
   "Tesis de Ingenieria Informatica",
   "Computacion",
   "Organizacion del Computador",
   "Organizacion de Datos",
   "Algoritmos y Programacion III",
   "Sistemas Operativos",
   "Analisis de la Informacion",
   "Tecnicas de Diseño",
   "Analisis Numerico",
   "Lenguajes Formales",
   "Base de Datos",
   "Lenguajes de Programacion",
   "Implantacion de Sistemas",
   "Proyectos Informaticos",
   "Teoria de Comunicacion",
   "Arquitecturas y Configuracion",
   "Concurrencia",
   "Inteligencia Artificial",
   "Teoria de la Programacion IV",
   "Simulacion",
   "Algoritmos y Programacion IV",
   "Teoria de Algoritmos I",
   "Teoria de Algoritmos II",
   "Teoria de Lenguaje",
   "Practica Profesional",
   "Redes y Teleprocesamientos I",
   "Redes y Teleprocesamientos II",
   "Seminario y Logica de Bases de Datos",
   "Analisis Numerico II A",
   "Aplicaciones Informaticas",
   "Algoritmos y Programacion I",
   "Algoritmos y Programacion II",
   "Taller de Programacion I",
   "Introduccion a los Sistemas Distribuidos",
   "Administracion y Control de Proyectos Informaticos I",
   "Taller de Desarrollo de Proyectos I",
   "Administracion y Control de Proyectos Informaticos II",
   "Taller de Desarrollo de Proyectos II",
   "Calidad en Desarrollo de Sistemas",
   "Introduccion a los Sistemas Inteligentes",
   "Tecnicas de Produccion de Software I",
   "Taller de Programacion II",
   "Tecnicas de Produccion de Software II",
   "Tecnicas de Produccion de Software III",
   "Organizacion de la Implantacion y el Mantenimiento",
   "Modelos de Proceso de Desarrollo",
   "Evaluacion de Proyectos y Manejo de Riesgos",
   "Tecnicas de Programacion Concurrente I",
   "Taller de Programacion III",
   "Tecnicas de Programacion Concurrente II",
   "Sistemas Distribuidos II",
   "Sistemas Multimediales",
   "Manufactura Integrada por Computadora I",
   "Manufactura Integrada por Computadora II",
   "Sistemas Automaticos de Diagnostico y Deteccion Fallas I",
   "Sistemas de Soporte para Celdas Produccion Flexible",
   "Sistemas Automaticos de Diagnostico y Deteccion Fallas II",
   "Sistemas de Programacion no convencional de Robots",
   "Seminario de Ingenieria de Informatica I",
   "Seminario de Ingenieria de Informatica II",
   "Arquitectura de Software",
   "Sistemas Distribuidos I",
   "Trabajo Profesional de Ingenieria Informatica",
   "Operaciones I",
   "Operaciones Unitarias II",
   "Operaciones Unitarias III",
   "Ingenieria de la Reacciones Quimicas",
   "Microbiologia Industrial",
   "Electroquimica",
   "Procesos Electroquimicos",
   "Fisicoquimica Especial",
   "Fundamentos de la Ing. de Reservorios",
   "Recuperacion Asistida de Petroleo",
   "Fundamentos de la Simulacion Numerica de Reservorio",
   "Explotacion de Yacimientos",
   "Control Estadistico de Procesos",
   "Gestion Recursos en la Industria de Procesos",
   "Industria de Procesos",
   "Industrias Alimenticias",
   "Introduccion a la Bioquimica",
   "Biotecnologia",
   "Ingenieria de la Instalaciones II B",
   "Instrumentacion y Control",
   "Termodinamica de los Procesos",
   "Introduccion a la Ingenieria Quimica",
   "Fenomenos de Transporte",
   "Evaluacion de Propiedades Fisicas",
   "Introduccion a la Planificacion Interactiva",
   "Operaciones Unitarias de Transferencia de Materia",
   "Diseño de Reactores",
   "Instalaciones de Plantas de Procesos",
   "Instrumentacion y Control de Plantas Quimicas",
   "Diseño de Procesos",
   "Emisiones de Contaminantes Quimicos y Biologicos",
   "Trabajo Profesional de Ingenieria Quimica",
   "Laboratorio de Operaciones y Procesos",
   "Bioingenieria",
   "Diseño Avanzado de Reactores",
   "Tesis de Ingenieria Quimica",
   "Termodinamica Aplicada a los Procesos Petroleros",
   "Tesis de Grado de Ingenieria de Alimentos",
   "Higiene y Seguridad del Trabajo",
   "Introduccion a la Ingenieria Ambiental",
   "Proyectos Nacionales e Ingenieria Ambiental",
   "Seguridad Ambiental y del Trabajo B",
   "Gestion Ambiental en la Industria Alimentaria",
   "Idioma Ingles",
   "Tesis de Ingenieria en Petroleo",
   "Introduccion a la Ingenieria en Petroleo",
   "Perforacion de Pozos I",
   "Terminacion y Reparacion de Pozos I",
   "Interpretacion de Registros de Pozos",
   "Geologia del Petroleo",
   "Geofisica del Petroleo",
   "Perforacion de Pozos II",
   "Ingenieria de Reservorios no Convencionales",
   "Gas y Condensados",
   "Desarrollo de Yacimientos",
   "Terminacion y Reparacion de Pozos II",
   "Produccion de Petroleo",
   "Evaluacion de Proyectos en Ingenieria en Petroleo",
   "Instalaciones de Produccion",
   "Integridad y Mantenimiento de Instalaciones de Produccion",
   "Caracterizacion Y Modelado De Reservorios",
   "Propiedades de la Roca y los Fluidos de Reservorios",
   "Ingenieria de Reservorios",
   "Ensayos de Pozo",
   "Recuperacion Secundaria y Asistida de Petroleo",
   "Simulacion Numerica de Reservorios",
   "Industrializacion del Petroleo y del Gas",
   "Tecnologia y Sociedad",
   "Energia Y Civilizacion",
   "Trabajo Profesional de Ingenieria en Petroleo",
   "Probabilidad y Estadistica A",
   "Analisis Matematico III B",
   "Analisis Matricial y Metodos Numericos",
   "Probabilidad",
   "Fisica I",
   "Fisica II",
   "Fisica III",
   "Fisica del Estado Solido",
   "Electromagnetismo",
   "Fisica III B",
   "Quimica Aplicada",
   "Quimica del Petroleo",
   "Introduccion a la Ingenieria Civil",
   "Estabilidad I",
   "Estabilidad II",
   "Comportamiento de Materiales",
   "Estatica y Resistencia de Materiales",
   "Estabilidad III",
   "Mecanica de Suelos y Geologia",
   "Estabilidad IV",
   "Seguridad estructural",
   "Dinamica de las estructuras",
   "Dinamica de las estructuras II",
   "Analisis sismico",
   "Trabajo profesional de Ingenieria Civil",
   "Tesis de Ingenieria Electricista",
   "Introduccion a la Ingenieria Electricista",
   "Electrotecnia",
   "Teoria de Circuitos y Sistemas",
   "Campos Electromagneticos",
   "Medidas Electricas",
   "Maquinas Electricas I",
   "Maquinas Electricas II",
   "Tecnologia de Materiales Electricos",
   "Diagnosticos Electricos y Ensayos",
   "Construcciones Electromecanicas",
   "Instalaciones de Baja Tension y Luminotecnia",
   "Sistemas Electricos de Potencia",
   "Centrales Electricas",
   "Transmision y Distribucion de la Energia Electrica",
   "Protecciones Electricas y Equipos de Maniobra",
   "Electronica de Potencia",
   "Economia de la Energia Electrica",
   "Accionamientos Electricos",
   "Luminotecnia",
   "Energias Renovables",
   "Uso Eficiente de la Energia Electrica",
   "Metrologia y Tecnicas de Calibracion Electrica",
   "Medicion de Magnitudes Fisicas por Medios Electricos",
   "Mediciones en AT",
   "Estaciones Transformadoras y de Distribucion",
   "Dinamica de SEP",
   "Comunicaciones y Telecontrol",
   "Seminario de Ingenieria Electricista I",
   "Seminario de Ingenieria Electricista II",
   "Proyecto de Centrales Hidroelectricas",
   "Proyecto de Centrales Termoelectricas",
   "Proyecto de Centrales Fotovoltaicas y Eolicas",
   "Abastecimiento Auxiliar de la Energia Electrica",
   "Regulacion de Servicios Publicos",
   "Electrotecnia General C",
   "Electrotecnia General",
   "Electrotecnia P",
   "Maquinas e Instalaciones Electricas",
   "Trabajo Profesional de Ingenieria Electricista ",
   "Tesis de Ingenieria Electronica",
   "Tecnica Digital",
   "Introduccion a la Ingenieria Electronica",
   "Dispositivos Semiconductores",
   "Circuitos Electronicos",
   "Laboratorio de Microprocesadores",
   "Control Automatico I",
   "Diseño de Circuitos Electronicos",
   "Teoria de la Informacion Codificacion",
   "Comunicacion de Datos",
   "Introduccion a Proyectos",
   "Control Automatico  II",
   "Control Automatico III",
   "Control Industrial Distribuido",
   "Control Robusto",
   "Identificacion y Control Adaptativo",
   "Instrumentacion y Control de Procesos",
   "Laboratorio de Control Automatico",
   "Accionamientos Variables",
   "Comunicaciones Digitales I",
   "Comunicaciones Digitales II",
   "Infraestructura de Redes Fijas",
   "Laboratorio de Comunicaciones",
   "Propagacion y Sistemas Irradiantes",
   "Comunicaciones Digitales III",
   "Servicios y Redes de Comunicaciones",
   "Sistemas Inalambricos",
   "Electronica",
   "Transmisores y Receptores de Comunicaciones",
   "Video Digital",
   "Redes de Computadoras",
   "Laboratorio de Redes de Computadoras",
   "Laboratorio de Sistemas Digitales",
   "Industrias y Productos de Electronica",
   "Microelectronica",
   "Optoelectronica",
   "Seminario de Electronica",
   "Seminario de Electronica II",
   "Tecnologia de los Componentes",
   "Procesamiento de Señales I",
   "Procesamiento de Señales II",
   "Teoria de Deteccion y Estimacion",
   "Acustica",
   "Electroacustica",
   "Audio Profesional",
   "Ingenieria Biomedica",
   "Equipamiento para Diagnostico y Tratamiento Biomedico",
   "Proc. y Analisis de Señales e Imagenes En Bioingenieria",
   "Compatibilidad Electromagnetica",
   "Sistemas Embebidos",
   "Laboratorio de Microelectronica",
   "Comunicaciones Radioelectricas y Radioenlaces",
   "Control no Lineal",
   "Instrumentos y Mediciones Electronicas",
   "Introduccion al Diseño Asistido por Computadora para Electronica",
   "Trabajo Profesional de Ingenieria Electronica",
   "Mecanica Aplicada",
   "Fuentes y Maquinas Energeticas",
   "Termodinamica y Mecanica de Fluidos",
   "Medios de Representacion A",
   "Mecanismos",
   "Medios de Representacion",
   "Termodinamica",
   "Taller A",
   "Maquinas Termicas",
   "Construccion de carreteras",
   "Diseño y operacion de caminos",
   "Puertos y Vias Navegables B",
   "Ferrocarriles B",
   "Aeropuertos B",
   "Transito",
   "Ingenieria Territorial",
   "Analisis de sistemas de transporte",
   "Caminos",
   "Aeropuertos A",
   "Ferrocarriles A",
   "Puertos y Vias Navegables A",
   "Evaluacion de proyectos",
   "Hidraulica General",
   "Centrales Hidraulicas",
   "Modelos Hidraulicos",
   "Hidrologia",
   "Planificacion de Recursos Hidraulicos",
   "Construcciones Hidraulicas",
   "Gestion Ambiental de los Recursos Hidricos",
   "Hidraulica Aplicada",
   "Aprovechamientos hidraulicos",
   "Ingenieria Sanitaria I",
   "Gestion Ambiental en Ingenieria Civil",
   "Hidraulica Fluvial",
   "Hidraulica Maritima",
   "Laboratorio de Hidraulica",
   "Ingenieria Sanitaria II",
   "Mecanica de Fluidos",
   "Transporte De Fluidos Por Tuberias",
   "Topografia y Geodesia",
   "Gerenciamiento y Organizacion de Obras Civiles",
   "Estadistica Aplicada I",
   "Investigacion Operativa I",
   "Organizacion Industrial III",
   "Organizacion Industrial I",
   "Legislacion y Ejercicio Profesional de la Ingenieria Electronica",
   "Organizacion Industrial II",
   "Informatica para la Gestion de Empresas",
   "Legislacion y Ejercicio Profesional de la Ingenieria Electricista",
   "Legislacion y Ejercicio Profesional de la Ingenieria Civil",
   "Introduccion a la Economia y la Organizacion en la Empresa",
   "Conflicto y Negociacion",
   "Ingeneria Legal para Ingeneria Industrial",
   "Macroeconomia y Estructura Economica Argentina",
   "Estadistica Aplicada III",
   "Direccion de Manufactura",
   "Logistica",
   "Gestion de Costos",
   "Ingeneria Economica A",
   "Estadistica Aplicada II",
   "Investigacion Operativa II",
   "Investigacion Operativa III",
   "Microeconomia Aplicada",
   "Gestion Financiera",
   "Analisis de Casos",
   "Gestion de la Calidad",
   "Emprendimientos de Ingenieria",
   "Estructuras y Procesos Organizacionales",
   "Legislacion y Ejercicio Profesional en Sistemas e Informatica",
   "Economia de las Organizaciones",
   "Administracion de las Organizaciones",
   "Herramientas de Gestion Profesional",
   "Legislacion y Ejercicio Profesional de Ingenieria en Petroleo",
   "Desarrollo y Gestion de Proyectos",
   "Gestion de la Innovacion",
   "Ciencia de Datos para la Toma de Decisiones",
   "Tesis de Ingenieria Industrial",
   "Industrias I",
   "Introduccion a la Ingenieria Industrial",
   "Procesos de Manufactura I",
   "Edificios Industriales",
   "Automatizacion Industrial y Robotica",
   "Instalaciones Industriales",
   "Diseño de Productos",
   "Industrias Plasticas",
   "Industrias de Celulosa y Papel",
   "Industrias Petroquimicas",
   "Industrias Textiles",
   "Materiales Industriales II",
   "Seminario de Ingenieria Industrial I",
   "Industrias de la Alimentacion",
   "Seminario de Ingenieria Industrial II",
   "Industrias Petroliferas",
   "Industrias II",
   "Procesos de Manufactura II",
   "Industria Automotriz",
   "Seminario de Ingenieria Industrial III",
   "Ingenieria y Desarrollo de Envaes y Embalajes",
   "Seminario de Ingenieria Industrial IV",
   "Trabajo Profesional de Ingenieria Industrial",
   "Hormigon I",
   "Arquitectura y Planificacion Urbana",
   "Construcciones",
   "Hormigon II",
   "Instalaciones en Obras Civiles I",
   "Presas",
   "Maquinarias de la Construccion",
   "Urbanismo",
   "Geotecnia Aplicada",
   "Estructuras Metalicas I",
   "Estructuras Metalicas II",
   "Tecnologia del Hormigon",
   "Patologia de la Construccion",
   "Estructuras de Madera",
   "Sistemas Constructivos",
   "Sistemas Estructurales",
   "Diseño Estructural",
   "Inspeccion y Ejecucion de Estructuras de Hormigon",
   "Materiales no tradicionales en la construccion",
   "Instalaciones en Obras Civiles II",
   "Teoria de Lenguajes de Programacion",
   "Modelacion numerica",
   "Metodos Matematicos y Numericos",
   "Metodos y Modelos en la Ingenieria de Software I",
   "Metodos y Modelos en la Ingenieria de Software II",
   "Estandares de Calidad y Modelos de Referencia",
   "Evaluacion e Implantacion de Sistemas",
   "Evaluacion de Proyectos y Manejo de  Riesgos",
   "Diseño Operacion y Gestion de Servicios Informaticos",
   "Redes y Aplicaciones Distribuidas",
   "Trabajo Profesional de Licenciatura en Analisis de Sistemas",
   "Innovacion Tecnologica",
   "Desarrollo de Aplicaciones Mainframe",
   "Auditoria de Sistemas",
   "Diseño y Desarrollo de Interfaces de Usuario",
   "Bases de Datos Multidimensionales",
   "Mineria de Datos",
   "Desarrollo con Nuevas Tecnologias",
   "Seminario de Sistemas de Informacion y Gestion",
   "Seminario de Metodologias de Desarrollo de Sistemas",
   "Arquitecturas y Configuraciones",
   "Higiene y Seguridad Industrial",
   "Higiene y Seguridad en Obras Civiles",
   "Seguridad Ambiental y del Trabajo",
   "Gestion Ambiental",
   "Gestion Ambiental para Ingenieria en Petroleo"
]